# Generated by Django 4.2.6 on 2023-12-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_userprofile_github"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
